### ISSUE TITLE
Question: Support of more experts in GPU

### ISSUE THREAD

**Issue by AGenchev** [ubergarm/r1-ktransformers-guide#13]
How to place experts in the VRAM ? I run it on A100/80 GB and notice the VRAM is almost empty. 
Ran on 4xA100/80 to test the yaml before edit. It worked. 
Then tried some suggested edits in the yaml, but inference fails (crashes) even if one expert is placed on the GPU. Here is the non-working edited part of DeepSeek-V3-Chat-multi-gpu-4.yaml with enabled 1 expert:
```
................
# === MLP Experts Replacement ===
# replace with marlin expert. Open and modify layer-num as needed.
# Each layer of malin experts takes about 6GB of GPU memory.
# !!!Do remember 'close' cuda graph if you are using marlin expert.!!!
# !!!KExpertsTorch is untested, we don't have enough VRAM.!!!

# GPU 0: layers 3–4
 - match:
     name: "^model\\.layers\\.([3-4])\\.mlp\\.experts$"
   replace:
     class: ktransformers.operators.experts.KTransformersExperts
     kwargs:
       generate_device: "cuda:0"
       generate_op:  "KExpertsMarlin"
   recursive: False

# # GPU 1: layers 15–17
# - match:
#     name: "^model\\.layers\\.(1[5-7])\\.mlp\\.experts$"
#   replace:
#     class: ktransformers.operators.experts.KTransformersExperts
#     kwargs:
#       generate_device: "cuda:1"
#       generate_op:  "KExpertsMarlin"
#   recursive: False
......................

```
The commandline is:
` USE_NUMA=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python3 /home/user/miniconda3/envs/py311ktrans/lib/python3.11/site-packages/ktransformers/server/main.py \`
 ` --gguf_path '/path/DeepSeek-R1-Q8_0_GGUF/'     --model_path 'deepseek-ai/DeepSeek-R1'  \`
 ` --model_name 'DeepSeek-R1-Q8_0'     --cpu_infer 24     --max_new_tokens 8192 \`
 ` --cache_lens 32768     --total_context 32768      --temperature 0.6     --top_p 0.95 \`
 ` --optimize_config_path 'ktransformers/try1_DeepSeek-V3-Chat-multi-gpu-4edit.yaml' \`
` --force_think          --host 127.0.0.1     --port 8080`
